name: A Season In The Life
favicon: null
layout_spectrum: 0.5430273551028222
typography_spectrum: 0.6662405414972454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22272b'
    - '#fbf6e1'
    - '#49919b'
    - '#c5c2b3'
    - '#a97503'
  brandStrength: 0.4375
  lightness: 0.4926499715074897
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
